services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: mackolik
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5433:5432" # Portu 5432 yerine 5433 olarak değiştirdim
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:1234@db:5432/mackolik
    command: >
      sh -c "until pg_isready -h db -p 5432 -U postgres; do
        echo Waiting for database;
        sleep 2;
      done;
      uvicorn main:app --host 0.0.0.0 --port 8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000

volumes:
  db_data: 